### PR TITLE
fixed a typo, change upstream font to loli.net

### PR DESCRIPTION
**Pull request by soloopooo**
To fix the DNS problem in mainland China, I changed the font link from googleapis to fonts.loli.net.

### CODE REVIEW

**Comment by soloopooo** [comment]
TODO:
Letting user choose upstream font server.(Google or Loli.net)

For @yurafuca  :

You can add a font-cdn switcher on index_cn.html.

The default cdn-server is https://fonts.googleapis.com/css?family=Noto+Sans+SC:900 and https://fonts.googleapis.com/css?family=Noto+Serif+SC:900 

The fallback cdn-server is https://fonts.loli.net/css?family=Noto+Sans+SC:900 and https://fonts.loli.net/css?family=Noto+Serif+SC:900.

Once the swicher template is completed, I can help find more usable and SAFE cdns for mainland China users. Thanks!

P.S. You can use Japanese to explain the use of cdn-switcher. I will help translate it once you finish your work.

**Comment by yurafuca** [comment]
Is https://fonts.loli.net always working properly?
If possible, I would like to always use  https://fonts.loli.net instead of adding a switcher.

**Comment by soloopooo** [comment]
Actually https://fonts.loli.net is a sub-domain of https://sm.ms. I prefer to add a swither instead of staticly using just ONE cdn, as the robustness and flex.

**Comment by yurafuca** [comment]
Adding a switcher is not technically difficult, but I want to keep the features of the generator as simple as possible.

Also, there may be some usability considerations. For example, we need to let the user choose which CDN is better, and we also need to add a way to let the user know if the CDN is not working properly or is unstable.

I will use https://fonts.loli.net statically for now, and consider adding a switcher in the future when problems arise.

Feel free to create Issues or Pull requests if you have any other requests.

**Comment by soloopooo** [comment]
Thanks. I will also try for a better solution.

**Pull request merged**
